const BlogsRouter = require('./blogs')
const commentsRouter = require('./comments')
const commentBlogsRouter = require('./commentBlogs')
const coursesRouter = require('./courses')
const topicsRouter = require('./topics')
const meRouter = require('./admin')
const authsRouter = require('./auth')
const usersRouter = require('./users')
const chatRouter = require('./chat')
const messageRouter = require('./message')
const loveBlogRouter = require('./loveBlog')
const oauth20 = require('./oauth20')
const takeNoteRouter = require('./takeNote')
const newFeedRouter = require('./newFeed')
const middlerwareVerify = require('../app/middleware/verifymidelware')
// const authrouter = require('./auth')

function route(app) {
    app.use('/api/admin', meRouter)
    app.use('/api/course', coursesRouter)
    app.use('/api/topic', topicsRouter)
    app.use('/api/auths', authsRouter)
    app.use('/api/authO2', oauth20)
    app.use('/api/users', middlerwareVerify.verifyToken, usersRouter)
    app.use('/api/chat', middlerwareVerify.verifyToken, chatRouter)
    app.use('/api/message', middlerwareVerify.verifyToken, messageRouter)
    app.use('/api/bookMark', middlerwareVerify.verifyToken, loveBlogRouter)
    app.use('/api/comment', middlerwareVerify.verifyToken, commentsRouter)
    app.use('/api/commentBlog', middlerwareVerify.verifyToken, commentBlogsRouter)
    app.use('/api/blog', BlogsRouter)
    app.use('/api/takeNote', middlerwareVerify.verifyToken, takeNoteRouter)
    app.use('/api/newFeed', newFeedRouter)
}

module.exports = route